# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: ibmcase/kcontainer-spring-container-ms
  tag: latest
  pullPolicy: Always
  pullSecret: null
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
service:
  name: Node
  type: NodePort
  servicePort: 8080
  nodePort: 31900
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  metrics:
    cpu:
      targetAverageUtilization: 70
    memory:
      targetAverageUtilization: 70
base:
  enabled: false
  replicaCount: 1
  image:
    tag : v0.9.9
  weight: 100
istio:
  enabled: false
  weight: 100
postgresql:
  capemRequired: false
  capemSecret: postgresql-ca-pem
  urlSecret: postgresql-url
  userSecret: postgresql-user
  passwordSecret: postgresql-pwd
kafka:
  brokersConfigMap: kafka-brokers
  orderTopicName: orders
  containerTopicName: containers
  rejectedOrdersTopicName: rejected-orders
  allocatedOrdersTopicName: allocated-orders
eventstreams:
  enabled: true
  apikeyConfigMap: eventstreams-apikey
  truststoreRequired: false
  truststorePath: /config/resources/security/es-ssl
  truststoreFile: es-cert.jks
  truststoreSecret: es-truststore-jks
  truststorePassword: changeit
bpm:
  anomalyConfigMap: bpm-anomaly
serviceAccountName: default
