# Default values for containerkstreams.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: us.icr.io/ibmcaseeda/kc-containerkstreams
  tag: latest
  pullPolicy: Always
  pullSecret: browncompute-registry-secret
  resources:
    requests:
      cpu: 200m
      memory: 400Mi
service:
  name: Node
  type: NodePort
  servicePort: 9080
  servicePortHttps: 9443
  nodePort: 31001

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - chart-example.local
  tls: []

istio:
  enabled: false
  weight: 100
generatedBindings:
  enabled: false
eventstreams:
  brokers: kafka03-prod02.messagehub.services.us-south.bluemix.net:9093,kafka01-prod02.messagehub.services.us-south.bluemix.net:9093,kafka02-prod02.messagehub.services.us-south.bluemix.net:9093,kafka04-prod02.messagehub.services.us-south.bluemix.net:9093,kafka05-prod02.messagehub.services.us-south.bluemix.net:9093
  env: IBMCLOUD
